# --------------------------------------------------------------
version_major_number: '3'
version_minor_number: '1'
version_patch_number: '4314'
version_suffix: ''
version_string: '3.1'
version_string_full: '3.1.4314'
version_date: '2016-03-27 03:00:06 +0200'
version_type: 'stable'
# --------------------------------------------------------------
core_name: 'Unitex'
ide_name: 'GramLab'
pack_name: 'Unitex-GramLab'
name: 'Unitex/GramLab'
logo: '/user/unitexgramlab.png'
# --------------------------------------------------------------
author_name: 'The Unitex/GramLab authors'
publisher_name: 'Université Paris-Est Marne-la-Vallée'
copyright_holder_name: 'Université Paris-Est Marne-la-Vallée'
# --------------------------------------------------------------
license_sources:  'LGPL'
license_resources: 'LGPLLR'
# --------------------------------------------------------------
url_releases: 'http://releases.unitexgramlab.org'
url_vinber_info: 'http://unitexgramlab.org/v6/#bundle=nightly&q=2016-03-27-03-00-06&line=1'
url_version_json: 'http://unitexgramlab.org/v6/badge/nightly/2016-03-27-03-00-06.json?subject=build.finished&status=product.version.string'
url_support: 'http://forum.unitexgramlab.org'
url_license_sources: 'https://opensource.org/licenses/lgpl-2.1'
url_license_resources: 'http://unitexgramlab.org/lgpllr'
# --------------------------------------------------------------
release_file:   'Unitex-GramLab-3.1{suffix}'
release_link:   'http://releases.unitexgramlab.org/3.1/{arch}/Unitex-GramLab-3.1{suffix}'
# --------------------------------------------------------------
release_linux32: 'http://releases.unitexgramlab.org/3.1/linux-i686/Unitex-GramLab-3.1-linux-i686.run'
release_linux64: 'http://releases.unitexgramlab.org/3.1/linux-x86_64/Unitex-GramLab-3.1-linux-x86_64.run'
release_osx:     'http://releases.unitexgramlab.org/3.1/osx/Unitex-GramLab-3.1-osx.run'
release_win32:   'http://releases.unitexgramlab.org/3.1/win32/Unitex-GramLab-3.1_win32-setup.exe'
release_win64:   'http://releases.unitexgramlab.org/3.1/win64/Unitex-GramLab-3.1_win64-setup.exe'
release_other:   'http://releases.unitexgramlab.org/3.1/source/Unitex-GramLab-3.1-source-distribution.zip'
release_manual:  'http://releases.unitexgramlab.org/3.1/man/Unitex-GramLab-3.1-usermanual-'
# --------------------------------------------------------------
usermanual_langs: [ en, fr ]
# --------------------------------------------------------------

